[package]
name = "BackupToUSB"
version = "0.1.0"
edition = "2024"  # Changed to 2024 edition
build = "build.rs"

[dependencies]
gtk = { version = "0.17", package = "gtk4" }
gio = "0.17"
dirs = "5.0"
fs_extra = "1.3"

[build-dependencies]
chrono = "0.4"
