[package]
name = "backuptousb"
version = "0.1.0-alpha"
edition = "2024"
build = "build.rs"

[dependencies]
gtk = { version = "0.10.3", package = "gtk4" }
gio = "0.21.5"
dirs = "6.0.0"
fs_extra = "1.3"
target-lexicon = "0.13.4"

[build-dependencies]
chrono = "0.4"
